/**
 * Situaciones para «Casos prácticos» y «Autoevaluación».
 * Cubren los 7 módulos y las 16 amenazas del catálogo.
 * `moduloSlug` = módulo (categoría) al que pertenece.
 * `amenazaSlug` = amenaza relacionada (/amenazas/[slug]), cuando aplica.
 * La opción segura es `correcta` (las opciones se barajan al mostrarse).
 */
export interface Escenario {
  id: string;
  titulo: string;
  situacion: string;
  opciones: string[];
  correcta: number;
  explicacion: string;
  tema: string;
  moduloSlug: string;
  amenazaSlug?: string;
}

export const ESCENARIOS: Escenario[] = [
  // ───────── Módulo 1 · Ingeniería social ─────────
  { id: 'is1', moduloSlug: 'ingenieria-social', amenazaSlug: 'ingenieria-social', tema: 'Ingeniería social', titulo: 'Amigo pidiendo dinero', situacion: 'Un contacto te escribe desde un número nuevo diciendo que tuvo un problema y necesita dinero urgente.', opciones: ['Envío el dinero, es mi amigo', 'Lo llamo a su número habitual para confirmar', 'Le pido que me explique más por chat'], correcta: 1, explicacion: 'Confirma siempre por otro canal conocido antes de enviar dinero. La urgencia es la herramienta favorita del engaño.' },
  { id: 'is2', moduloSlug: 'ingenieria-social', amenazaSlug: 'suplantacion-identidad', tema: 'Suplantación de identidad', titulo: 'Un perfil con tu nombre y tus fotos', situacion: 'Un compañero te avisa que existe un perfil con tu nombre y tus fotos que está pidiendo dinero a tus contactos.', opciones: ['Lo ignoro, seguro se cansan', 'Reporto el perfil, aviso a mis contactos y reviso la privacidad de mis cuentas', 'Escribo al perfil falso para insultarlo'], correcta: 1, explicacion: 'Reportar, avisar a tus contactos y limitar lo que publicas reduce el daño. Responderle al perfil falso no sirve.' },
  { id: 'is3', moduloSlug: 'ingenieria-social', amenazaSlug: 'deepfakes', tema: 'Deepfakes', titulo: 'Audio de un familiar', situacion: 'Recibes un audio con la voz de un familiar pidiendo dinero urgente y que no avises a nadie.', opciones: ['Envío el dinero, reconozco su voz', 'Lo llamo al número que ya tengo para confirmar', 'Le pido una foto por el mismo chat'], correcta: 1, explicacion: 'La voz puede imitarse con IA. Verifica por un canal que ya conoces; pedir una foto por el mismo chat tampoco es seguro.' },

  // ───────── Módulo 2 · Phishing y fraudes digitales ─────────
  { id: 'ph1', moduloSlug: 'phishing', amenazaSlug: 'phishing', tema: 'Phishing', titulo: 'Cuenta a punto de bloquearse', situacion: 'Recibes un mensaje urgente indicando que tu cuenta será bloqueada y contiene un enlace. ¿Qué harías?', opciones: ['Hacer clic rápido para evitar el bloqueo', 'No usar el enlace y entrar desde la página oficial', 'Responder el mensaje pidiendo más información'], correcta: 1, explicacion: 'Los mensajes urgentes con enlaces son típicos del phishing. Entra siempre escribiendo tú la dirección oficial.' },
  { id: 'ph2', moduloSlug: 'phishing', amenazaSlug: 'smishing', tema: 'Smishing', titulo: 'Paquete retenido', situacion: 'Te llega un SMS: «Tu paquete no pudo entregarse, confirma tus datos aquí». No esperabas ningún paquete.', opciones: ['Abro el enlace por curiosidad', 'Ignoro y borro el mensaje', 'Lo reenvío a un amigo para que lo revise'], correcta: 1, explicacion: 'Si no esperas un envío, ignora el mensaje. Reenviarlo expone a otras personas.' },
  { id: 'ph3', moduloSlug: 'phishing', amenazaSlug: 'vishing', tema: 'Vishing', titulo: 'Llamada del banco', situacion: 'Alguien dice ser del banco y te pide el código que acaba de llegar a tu teléfono para «cancelar una compra».', opciones: ['Le doy el código', 'Cuelgo y llamo al número oficial del banco', 'Le doy solo los últimos dígitos'], correcta: 1, explicacion: 'Los códigos de verificación son personales. Ningún banco te los pide por llamada.' },
  { id: 'ph4', moduloSlug: 'phishing', amenazaSlug: 'quishing', tema: 'Quishing', titulo: 'QR sospechoso', situacion: 'Ves un QR pegado en un poste que promete internet gratis si inicias sesión con tu cuenta.', opciones: ['Lo escaneo e inicio sesión', 'No lo escaneo', 'Lo escaneo pero con una cuenta que no uso'], correcta: 1, explicacion: 'Los QR de origen desconocido pueden llevar a páginas falsas. Es mejor no escanearlos.' },
  { id: 'ph5', moduloSlug: 'phishing', amenazaSlug: 'enlaces-maliciosos', tema: 'Enlaces maliciosos', titulo: 'Un amigo te manda un enlace raro', situacion: 'Un amigo te envía «mira esta foto tuya» con un enlace acortado, sin más texto. No suele escribirte así.', opciones: ['Abro el enlace, es mi amigo', 'Le pregunto por otro medio si realmente lo envió', 'Lo abro desde la computadora, que es más segura'], correcta: 1, explicacion: 'La cuenta de tu amigo pudo ser hackeada. Pregunta por otro medio antes de abrir un enlace fuera de contexto.' },

  // ───────── Módulo 3 · Malware ─────────
  { id: 'ma1', moduloSlug: 'malware', amenazaSlug: 'troyanos', tema: 'Troyanos', titulo: 'Programa «gratis»', situacion: 'Encuentras un programa de pago «gratis» en un sitio desconocido.', opciones: ['Lo descargo, es gratis', 'Lo evito y busco una alternativa oficial o gratuita legítima', 'Lo descargo y desactivo el antivirus'], correcta: 1, explicacion: 'El software pirata es una vía común de troyanos y otro malware. Usa fuentes oficiales.' },
  { id: 'ma2', moduloSlug: 'malware', amenazaSlug: 'ransomware', tema: 'Ransomware', titulo: 'Adjunto de «factura»', situacion: 'Te llega un correo de un remitente desconocido con un adjunto llamado «factura pendiente».', opciones: ['Lo abro para ver de qué se trata', 'No lo abro y elimino el correo', 'Lo descargo y lo abro en otro equipo'], correcta: 1, explicacion: 'Los adjuntos inesperados son una vía clásica del ransomware. Además, mantén copias de seguridad de tus trabajos.' },
  { id: 'ma3', moduloSlug: 'malware', amenazaSlug: 'spyware', tema: 'Spyware', titulo: 'Linterna que pide permisos', situacion: 'Una app de linterna te pide acceso a tus contactos, micrófono y ubicación.', opciones: ['Acepto todo para que funcione', 'Rechazo, desinstalo y busco una app de un desarrollador confiable', 'Acepto solo el micrófono'], correcta: 1, explicacion: 'Una linterna no necesita esos permisos. Pedir de más es señal de posible spyware.' },
  { id: 'ma4', moduloSlug: 'malware', amenazaSlug: 'malware', tema: 'Malware', titulo: 'USB encontrada', situacion: 'Encuentras una memoria USB en el pasillo de la universidad.', opciones: ['La conecto para ver de quién es', 'No la conecto y la entrego al área responsable', 'La conecto en una computadora vieja'], correcta: 1, explicacion: 'Una USB desconocida puede traer malware. No la conectes a ningún equipo.' },

  // ───────── Módulo 4 · Contraseñas y autenticación ─────────
  { id: 'co1', moduloSlug: 'contrasenas', amenazaSlug: 'robo-credenciales', tema: 'Robo de credenciales', titulo: 'Una clave para todo', situacion: 'Usas la misma contraseña en tu correo, redes y cuenta bancaria porque es fácil de recordar.', opciones: ['Está bien si es larga', 'Es riesgoso: si se filtra en un sitio, caen todas', 'Es seguro si la cambio una vez al año'], correcta: 1, explicacion: 'Reutilizar contraseñas permite que una filtración afecte todas tus cuentas. Usa claves únicas.' },
  { id: 'co2', moduloSlug: 'contrasenas', tema: 'Autenticación multifactor', titulo: 'Verificación en dos pasos', situacion: 'Tu correo te sugiere activar la verificación en dos pasos. Piensas que es una molestia.', opciones: ['La ignoro, ya tengo contraseña', 'La activo: aunque roben mi clave, no podrán entrar solos', 'La activo pero comparto el código con mi pareja'], correcta: 1, explicacion: 'La verificación en dos pasos añade una barrera extra. Los códigos son personales: no se comparten con nadie.' },
  { id: 'co3', moduloSlug: 'contrasenas', amenazaSlug: 'robo-credenciales', tema: 'Robo de credenciales', titulo: 'Inicio de sesión desde otro lugar', situacion: 'Te llega un aviso de que alguien inició sesión en tu cuenta desde otro país.', opciones: ['Lo ignoro, seguro es un error', 'Cambio la contraseña, cierro las sesiones abiertas y reviso mi cuenta', 'Espero a ver si vuelve a pasar'], correcta: 1, explicacion: 'Actúa de inmediato: cambia la clave, cierra sesiones activas y revisa la actividad de la cuenta.' },

  // ───────── Módulo 5 · Privacidad y protección de datos ─────────
  { id: 'pr1', moduloSlug: 'privacidad-datos', tema: 'Datos personales', titulo: 'Foto de tu tarjeta', situacion: 'Quieres enviar a un amigo una foto de tu tarjeta para que te ayude con una compra.', opciones: ['Se la envío, es mi amigo', 'No la envío y busco otra forma de pago', 'La envío y la borro luego'], correcta: 1, explicacion: 'Los datos de tu tarjeta no deben compartirse ni fotografiarse; pueden quedar guardados o filtrarse.' },
  { id: 'pr2', moduloSlug: 'privacidad-datos', tema: 'Permisos de aplicaciones', titulo: 'Permisos al instalar una app', situacion: 'Instalas una app nueva y te pide acceso a fotos, contactos y ubicación «siempre».', opciones: ['Acepto todo sin leer', 'Doy solo los permisos necesarios y reviso el resto después', 'Acepto y luego me olvido'], correcta: 1, explicacion: 'Da a cada app solo lo que necesita y revisa tus permisos de vez en cuando.' },
  { id: 'pr3', moduloSlug: 'privacidad-datos', tema: 'Huella digital', titulo: 'Publicar tu viaje', situacion: 'Vas de viaje y quieres publicar fotos con ubicación exacta y fechas mientras estás fuera de casa.', opciones: ['Publico todo en tiempo real', 'Publico después del viaje y sin ubicación exacta', 'Publico con el perfil abierto para más alcance'], correcta: 1, explicacion: 'Publicar después y sin ubicación exacta reduce riesgos como robos o seguimiento.' },

  // ───────── Módulo 6 · Redes sociales ─────────
  { id: 'rs1', moduloSlug: 'redes-sociales', amenazaSlug: 'fraudes-redes-sociales', tema: 'Fraudes en redes sociales', titulo: 'Sorteo que pide tus datos', situacion: 'Una cuenta te dice que ganaste un sorteo que no recuerdas haber jugado y te pide tus datos y compartir la publicación.', opciones: ['Envío mis datos para recibir el premio', 'Desconfío, no doy datos y reporto la cuenta', 'Comparto la publicación para que más gente participe'], correcta: 1, explicacion: 'Los sorteos que piden datos y que los compartas son una táctica común de fraude.' },
  { id: 'rs2', moduloSlug: 'redes-sociales', amenazaSlug: 'fraudes-redes-sociales', tema: 'Compras en redes', titulo: 'Celular a mitad de precio', situacion: 'Un perfil nuevo vende un celular a mitad de precio y pide el pago por adelantado.', opciones: ['Pago rápido antes de que se acabe', 'Desconfío y no pago por adelantado', 'Pido más fotos y luego pago'], correcta: 1, explicacion: 'Precios irreales y pago por adelantado son señales clásicas de estafa.' },
  { id: 'rs3', moduloSlug: 'redes-sociales', tema: 'Privacidad en redes', titulo: 'Solicitud de un desconocido', situacion: 'Un perfil que no conoces te envía una solicitud de amistad y tu cuenta es pública.', opciones: ['Acepto, mientras más seguidores mejor', 'No acepto y reviso que mi perfil sea privado', 'Acepto y le escribo para conocerlo'], correcta: 1, explicacion: 'Acepta solo a personas que conoces y limita quién puede ver tus publicaciones.' },

  // ───────── Módulo 7 · Seguridad de dispositivos y redes ─────────
  { id: 'wf1', moduloSlug: 'redes-wifi', amenazaSlug: 'wifi-publico-inseguro', tema: 'Wi-Fi público', titulo: 'Wi-Fi gratis en la cafetería', situacion: 'Necesitas hacer una transferencia y solo hay un Wi-Fi abierto en el local.', opciones: ['Me conecto y la hago', 'Uso mis datos móviles', 'Pido la clave a cualquier persona del lugar'], correcta: 1, explicacion: 'Para operaciones sensibles es mejor usar datos móviles que una red abierta.' },
  { id: 'wf2', moduloSlug: 'redes-wifi', amenazaSlug: 'aplicaciones-falsas', tema: 'Aplicaciones falsas', titulo: '«Versión premium gratis»', situacion: 'Un enlace te ofrece la «versión premium gratis» de tu red social favorita, para instalar fuera de la tienda oficial.', opciones: ['La instalo, es gratis', 'No la instalo: solo descargo apps de la tienda oficial', 'La instalo pero sin iniciar sesión'], correcta: 1, explicacion: 'Las apps que imitan a las originales roban cuentas. Descarga siempre desde tiendas oficiales.' },
  { id: 'wf3', moduloSlug: 'redes-wifi', tema: 'Actualizaciones', titulo: 'Actualización pendiente', situacion: 'Tu teléfono lleva meses avisándote que hay una actualización de seguridad pendiente.', opciones: ['La sigo posponiendo', 'La instalo: las actualizaciones corrigen fallas de seguridad', 'La desactivo para que no moleste'], correcta: 1, explicacion: 'Las actualizaciones corrigen vulnerabilidades. Activarlas en automático es una de las mejores defensas.' },
];

export const TOTAL_AMENAZAS_CUBIERTAS = new Set(ESCENARIOS.map((e) => e.amenazaSlug).filter(Boolean)).size;
