-- Banco de preguntas de la Autoevaluación, gestionable desde el panel (/admin/autoevaluaciones).
CREATE TABLE IF NOT EXISTS "preguntas_autoevaluacion" (
    "id" TEXT NOT NULL,
    "moduloSlug" TEXT NOT NULL,
    "amenazaSlug" TEXT,
    "tema" TEXT NOT NULL,
    "titulo" TEXT NOT NULL,
    "situacion" TEXT NOT NULL,
    "opciones" TEXT[],
    "correcta" INTEGER NOT NULL,
    "explicacion" TEXT NOT NULL,
    "orden" INTEGER NOT NULL DEFAULT 0,
    "activa" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "preguntas_autoevaluacion_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "preguntas_autoevaluacion_activa_orden_idx" ON "preguntas_autoevaluacion"("activa", "orden");

-- Precarga: las 24 preguntas que ya usaba la autoevaluación (lib/escenarios-data.ts),
-- con los mismos ids. ON CONFLICT evita duplicarlas si la migración se aplica de nuevo.
INSERT INTO "preguntas_autoevaluacion" ("id", "moduloSlug", "amenazaSlug", "tema", "titulo", "situacion", "opciones", "correcta", "explicacion", "orden", "activa", "updatedAt") VALUES
  ('is1', 'ingenieria-social', 'ingenieria-social', 'Ingeniería social', 'Amigo pidiendo dinero', 'Un contacto te escribe desde un número nuevo diciendo que tuvo un problema y necesita dinero urgente.', ARRAY['Envío el dinero, es mi amigo', 'Lo llamo a su número habitual para confirmar', 'Le pido que me explique más por chat']::TEXT[], 1, 'Confirma siempre por otro canal conocido antes de enviar dinero. La urgencia es la herramienta favorita del engaño.', 1, true, CURRENT_TIMESTAMP),
  ('is2', 'ingenieria-social', 'suplantacion-identidad', 'Suplantación de identidad', 'Un perfil con tu nombre y tus fotos', 'Un compañero te avisa que existe un perfil con tu nombre y tus fotos que está pidiendo dinero a tus contactos.', ARRAY['Lo ignoro, seguro se cansan', 'Reporto el perfil, aviso a mis contactos y reviso la privacidad de mis cuentas', 'Escribo al perfil falso para insultarlo']::TEXT[], 1, 'Reportar, avisar a tus contactos y limitar lo que publicas reduce el daño. Responderle al perfil falso no sirve.', 2, true, CURRENT_TIMESTAMP),
  ('is3', 'ingenieria-social', 'deepfakes', 'Deepfakes', 'Audio de un familiar', 'Recibes un audio con la voz de un familiar pidiendo dinero urgente y que no avises a nadie.', ARRAY['Envío el dinero, reconozco su voz', 'Lo llamo al número que ya tengo para confirmar', 'Le pido una foto por el mismo chat']::TEXT[], 1, 'La voz puede imitarse con IA. Verifica por un canal que ya conoces; pedir una foto por el mismo chat tampoco es seguro.', 3, true, CURRENT_TIMESTAMP),
  ('ph1', 'phishing', 'phishing', 'Phishing', 'Cuenta a punto de bloquearse', 'Recibes un mensaje urgente indicando que tu cuenta será bloqueada y contiene un enlace. ¿Qué harías?', ARRAY['Hacer clic rápido para evitar el bloqueo', 'No usar el enlace y entrar desde la página oficial', 'Responder el mensaje pidiendo más información']::TEXT[], 1, 'Los mensajes urgentes con enlaces son típicos del phishing. Entra siempre escribiendo tú la dirección oficial.', 4, true, CURRENT_TIMESTAMP),
  ('ph2', 'phishing', 'smishing', 'Smishing', 'Paquete retenido', 'Te llega un SMS: «Tu paquete no pudo entregarse, confirma tus datos aquí». No esperabas ningún paquete.', ARRAY['Abro el enlace por curiosidad', 'Ignoro y borro el mensaje', 'Lo reenvío a un amigo para que lo revise']::TEXT[], 1, 'Si no esperas un envío, ignora el mensaje. Reenviarlo expone a otras personas.', 5, true, CURRENT_TIMESTAMP),
  ('ph3', 'phishing', 'vishing', 'Vishing', 'Llamada del banco', 'Alguien dice ser del banco y te pide el código que acaba de llegar a tu teléfono para «cancelar una compra».', ARRAY['Le doy el código', 'Cuelgo y llamo al número oficial del banco', 'Le doy solo los últimos dígitos']::TEXT[], 1, 'Los códigos de verificación son personales. Ningún banco te los pide por llamada.', 6, true, CURRENT_TIMESTAMP),
  ('ph4', 'phishing', 'quishing', 'Quishing', 'QR sospechoso', 'Ves un QR pegado en un poste que promete internet gratis si inicias sesión con tu cuenta.', ARRAY['Lo escaneo e inicio sesión', 'No lo escaneo', 'Lo escaneo pero con una cuenta que no uso']::TEXT[], 1, 'Los QR de origen desconocido pueden llevar a páginas falsas. Es mejor no escanearlos.', 7, true, CURRENT_TIMESTAMP),
  ('ph5', 'phishing', 'enlaces-maliciosos', 'Enlaces maliciosos', 'Un amigo te manda un enlace raro', 'Un amigo te envía «mira esta foto tuya» con un enlace acortado, sin más texto. No suele escribirte así.', ARRAY['Abro el enlace, es mi amigo', 'Le pregunto por otro medio si realmente lo envió', 'Lo abro desde la computadora, que es más segura']::TEXT[], 1, 'La cuenta de tu amigo pudo ser hackeada. Pregunta por otro medio antes de abrir un enlace fuera de contexto.', 8, true, CURRENT_TIMESTAMP),
  ('ma1', 'malware', 'troyanos', 'Troyanos', 'Programa «gratis»', 'Encuentras un programa de pago «gratis» en un sitio desconocido.', ARRAY['Lo descargo, es gratis', 'Lo evito y busco una alternativa oficial o gratuita legítima', 'Lo descargo y desactivo el antivirus']::TEXT[], 1, 'El software pirata es una vía común de troyanos y otro malware. Usa fuentes oficiales.', 9, true, CURRENT_TIMESTAMP),
  ('ma2', 'malware', 'ransomware', 'Ransomware', 'Adjunto de «factura»', 'Te llega un correo de un remitente desconocido con un adjunto llamado «factura pendiente».', ARRAY['Lo abro para ver de qué se trata', 'No lo abro y elimino el correo', 'Lo descargo y lo abro en otro equipo']::TEXT[], 1, 'Los adjuntos inesperados son una vía clásica del ransomware. Además, mantén copias de seguridad de tus trabajos.', 10, true, CURRENT_TIMESTAMP),
  ('ma3', 'malware', 'spyware', 'Spyware', 'Linterna que pide permisos', 'Una app de linterna te pide acceso a tus contactos, micrófono y ubicación.', ARRAY['Acepto todo para que funcione', 'Rechazo, desinstalo y busco una app de un desarrollador confiable', 'Acepto solo el micrófono']::TEXT[], 1, 'Una linterna no necesita esos permisos. Pedir de más es señal de posible spyware.', 11, true, CURRENT_TIMESTAMP),
  ('ma4', 'malware', 'malware', 'Malware', 'USB encontrada', 'Encuentras una memoria USB en el pasillo de la universidad.', ARRAY['La conecto para ver de quién es', 'No la conecto y la entrego al área responsable', 'La conecto en una computadora vieja']::TEXT[], 1, 'Una USB desconocida puede traer malware. No la conectes a ningún equipo.', 12, true, CURRENT_TIMESTAMP),
  ('co1', 'contrasenas', 'robo-credenciales', 'Robo de credenciales', 'Una clave para todo', 'Usas la misma contraseña en tu correo, redes y cuenta bancaria porque es fácil de recordar.', ARRAY['Está bien si es larga', 'Es riesgoso: si se filtra en un sitio, caen todas', 'Es seguro si la cambio una vez al año']::TEXT[], 1, 'Reutilizar contraseñas permite que una filtración afecte todas tus cuentas. Usa claves únicas.', 13, true, CURRENT_TIMESTAMP),
  ('co2', 'contrasenas', NULL, 'Autenticación multifactor', 'Verificación en dos pasos', 'Tu correo te sugiere activar la verificación en dos pasos. Piensas que es una molestia.', ARRAY['La ignoro, ya tengo contraseña', 'La activo: aunque roben mi clave, no podrán entrar solos', 'La activo pero comparto el código con mi pareja']::TEXT[], 1, 'La verificación en dos pasos añade una barrera extra. Los códigos son personales: no se comparten con nadie.', 14, true, CURRENT_TIMESTAMP),
  ('co3', 'contrasenas', 'robo-credenciales', 'Robo de credenciales', 'Inicio de sesión desde otro lugar', 'Te llega un aviso de que alguien inició sesión en tu cuenta desde otro país.', ARRAY['Lo ignoro, seguro es un error', 'Cambio la contraseña, cierro las sesiones abiertas y reviso mi cuenta', 'Espero a ver si vuelve a pasar']::TEXT[], 1, 'Actúa de inmediato: cambia la clave, cierra sesiones activas y revisa la actividad de la cuenta.', 15, true, CURRENT_TIMESTAMP),
  ('pr1', 'privacidad-datos', NULL, 'Datos personales', 'Foto de tu tarjeta', 'Quieres enviar a un amigo una foto de tu tarjeta para que te ayude con una compra.', ARRAY['Se la envío, es mi amigo', 'No la envío y busco otra forma de pago', 'La envío y la borro luego']::TEXT[], 1, 'Los datos de tu tarjeta no deben compartirse ni fotografiarse; pueden quedar guardados o filtrarse.', 16, true, CURRENT_TIMESTAMP),
  ('pr2', 'privacidad-datos', NULL, 'Permisos de aplicaciones', 'Permisos al instalar una app', 'Instalas una app nueva y te pide acceso a fotos, contactos y ubicación «siempre».', ARRAY['Acepto todo sin leer', 'Doy solo los permisos necesarios y reviso el resto después', 'Acepto y luego me olvido']::TEXT[], 1, 'Da a cada app solo lo que necesita y revisa tus permisos de vez en cuando.', 17, true, CURRENT_TIMESTAMP),
  ('pr3', 'privacidad-datos', NULL, 'Huella digital', 'Publicar tu viaje', 'Vas de viaje y quieres publicar fotos con ubicación exacta y fechas mientras estás fuera de casa.', ARRAY['Publico todo en tiempo real', 'Publico después del viaje y sin ubicación exacta', 'Publico con el perfil abierto para más alcance']::TEXT[], 1, 'Publicar después y sin ubicación exacta reduce riesgos como robos o seguimiento.', 18, true, CURRENT_TIMESTAMP),
  ('rs1', 'redes-sociales', 'fraudes-redes-sociales', 'Fraudes en redes sociales', 'Sorteo que pide tus datos', 'Una cuenta te dice que ganaste un sorteo que no recuerdas haber jugado y te pide tus datos y compartir la publicación.', ARRAY['Envío mis datos para recibir el premio', 'Desconfío, no doy datos y reporto la cuenta', 'Comparto la publicación para que más gente participe']::TEXT[], 1, 'Los sorteos que piden datos y que los compartas son una táctica común de fraude.', 19, true, CURRENT_TIMESTAMP),
  ('rs2', 'redes-sociales', 'fraudes-redes-sociales', 'Compras en redes', 'Celular a mitad de precio', 'Un perfil nuevo vende un celular a mitad de precio y pide el pago por adelantado.', ARRAY['Pago rápido antes de que se acabe', 'Desconfío y no pago por adelantado', 'Pido más fotos y luego pago']::TEXT[], 1, 'Precios irreales y pago por adelantado son señales clásicas de estafa.', 20, true, CURRENT_TIMESTAMP),
  ('rs3', 'redes-sociales', NULL, 'Privacidad en redes', 'Solicitud de un desconocido', 'Un perfil que no conoces te envía una solicitud de amistad y tu cuenta es pública.', ARRAY['Acepto, mientras más seguidores mejor', 'No acepto y reviso que mi perfil sea privado', 'Acepto y le escribo para conocerlo']::TEXT[], 1, 'Acepta solo a personas que conoces y limita quién puede ver tus publicaciones.', 21, true, CURRENT_TIMESTAMP),
  ('wf1', 'redes-wifi', 'wifi-publico-inseguro', 'Wi-Fi público', 'Wi-Fi gratis en la cafetería', 'Necesitas hacer una transferencia y solo hay un Wi-Fi abierto en el local.', ARRAY['Me conecto y la hago', 'Uso mis datos móviles', 'Pido la clave a cualquier persona del lugar']::TEXT[], 1, 'Para operaciones sensibles es mejor usar datos móviles que una red abierta.', 22, true, CURRENT_TIMESTAMP),
  ('wf2', 'redes-wifi', 'aplicaciones-falsas', 'Aplicaciones falsas', '«Versión premium gratis»', 'Un enlace te ofrece la «versión premium gratis» de tu red social favorita, para instalar fuera de la tienda oficial.', ARRAY['La instalo, es gratis', 'No la instalo: solo descargo apps de la tienda oficial', 'La instalo pero sin iniciar sesión']::TEXT[], 1, 'Las apps que imitan a las originales roban cuentas. Descarga siempre desde tiendas oficiales.', 23, true, CURRENT_TIMESTAMP),
  ('wf3', 'redes-wifi', NULL, 'Actualizaciones', 'Actualización pendiente', 'Tu teléfono lleva meses avisándote que hay una actualización de seguridad pendiente.', ARRAY['La sigo posponiendo', 'La instalo: las actualizaciones corrigen fallas de seguridad', 'La desactivo para que no moleste']::TEXT[], 1, 'Las actualizaciones corrigen vulnerabilidades. Activarlas en automático es una de las mejores defensas.', 24, true, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
